export const BITS_PER_COMPONENT = 18;
export const BITS_FOR_ROTATION = 5;
export const ROT_MASK = (1 << BITS_FOR_ROTATION) - 1;
export const Y_BITS_OFFSET = BITS_PER_COMPONENT;
export const Z_BITS_OFFSET = Y_BITS_OFFSET + BITS_PER_COMPONENT;
export const ROTATION_BITS_OFFSET = Z_BITS_OFFSET + BITS_PER_COMPONENT;
export const UNUSED_BITS_OFFSET = ROTATION_BITS_OFFSET + BITS_FOR_ROTATION;
export const ENCODED_POSITION_MAX_VALUE = (1 << BITS_PER_COMPONENT) - 1;
